4 TO-DO-Task<br>
4.1 Exercise on Functions:<br>
Task- 1:<br>

In [22]:
def convert_units(conversion_type, value):
    """
    Converts between different units of measurement.

    Parameters:
    conversion_type (str): Type of conversion chosen by user
    value (float): numeric value to convert

    Returns:
    float: converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084

    elif conversion_type == "ft_to_m":
        return value / 3.28084

    elif conversion_type == "kg_to_lb":
        return value * 2.20462

    elif conversion_type == "lb_to_kg":
        return value / 2.20462

    elif conversion_type == "l_to_gal":
        return value * 0.264172

    elif conversion_type == "gal_to_l":
        return value / 0.264172

    else:
        raise ValueError("Unsupported conversion type")


def main():
    print("Choose conversion type:")
    print("1: meters → feet")
    print("2: feet → meters")
    print("3: kg → pounds")
    print("4: pounds → kg")
    print("5: liters → gallons")
    print("6: gallons → liters")

    choice = input("Enter choice (1-6): ")

    try:
        value = float(input("Enter value: "))

        conversions = {
            "1": "m_to_ft",
            "2": "ft_to_m",
            "3": "kg_to_lb",
            "4": "lb_to_kg",
            "5": "l_to_gal",
            "6": "gal_to_l"
        }

        result = convert_units(conversions[choice], value)

        print("Converted value:", result)

    except ValueError:
        print("Invalid input. Please enter numeric values.")

    except KeyError:
        print("Invalid conversion option.")


main()

Choose conversion type:
1: meters → feet
2: feet → meters
3: kg → pounds
4: pounds → kg
5: liters → gallons
6: gallons → liters
Enter choice (1-6): 1
Enter value: 2
Converted value: 6.56168


Task- 2:

In [23]:
def find_sum(numbers):
    """Returns the sum of numbers"""
    return sum(numbers)


def find_average(numbers):
    """Returns the average of numbers"""
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """Returns the maximum number"""
    return max(numbers)


def find_min(numbers):
    """Returns the minimum number"""
    return min(numbers)


def main():

    try:
        nums = input("Enter numbers separated by space: ")

        numbers = [float(x) for x in nums.split()]

        if len(numbers) == 0:
            raise ValueError("List cannot be empty")

        print("Choose operation:")
        print("1 Sum")
        print("2 Average")
        print("3 Maximum")
        print("4 Minimum")

        choice = input("Enter choice: ")

        if choice == "1":
            print("Sum:", find_sum(numbers))

        elif choice == "2":
            print("Average:", find_average(numbers))

        elif choice == "3":
            print("Maximum:", find_max(numbers))

        elif choice == "4":
            print("Minimum:", find_min(numbers))

        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input. Enter numbers only.")


main()

Enter numbers separated by space: 1 2
Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Enter choice: 2
Average: 1.5


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:

In [24]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2. Slice a Sublist:

In [25]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3. Reverse a List Using Slicing:

In [26]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

In [27]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5. Get the First n Elements:

In [28]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6. Extract Elements from the End:

In [29]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


7. Extract Elements in Reverse Order:


In [30]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:

In [31]:
def flatten(lst):
    result = []
    for sub in lst:
        result.extend(sub)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:


In [32]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


3. Sum of All Elements in a Nested List:

In [33]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total
print(sum_nested([[1,2],[3,[4,5]],6]))

21


4. Remove Specific Element from a Nested List:


In [34]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        else:
            if item != elem:
                result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:


In [35]:
def find_max(lst):
    maximum = float("-inf")

    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


6. Count Occurrences of an Element in a Nested List:


In [36]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        elif item == elem:
            count += 1

    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


7. Flatten a List of Lists of Lists:


In [37]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:


In [38]:
def average_nested(lst):

    flat = deep_flatten(lst)

    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


10 To- Do- NumPy <br>
10.1 Basic Vector and Matrix Operation with Numpy.<br>
Problem- 1: Array Creation:<br>

In [51]:
import numpy as np

In [52]:
# 1
arr1 = np.empty((2,2))
print("Empty array:\n",arr1)

# 2
arr2 = np.ones((4,2))
print("\nOnes array:\n",arr2)

# 3
arr3 = np.full((3,3),7)
print("\nFull array:\n",arr3)

# 4
arr4 = np.zeros_like(arr3)
print("\nZeros like:\n",arr4)

# 5
arr5 = np.ones_like(arr3)
print("\nOnes like:\n",arr5)

# 6
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nConverted list to numpy array:\n",arr6)

Empty array:
 [[5.04682251e-315 0.00000000e+000]
 [5.73116149e-322 6.82369286e-310]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted list to numpy array:
 [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:


1. Create an array with values ranging from 10 to 49.


In [53]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.


In [54]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.


In [55]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.


In [56]:
arr = np.random.random(30)

print(arr)
print("Mean:", arr.mean())

[0.13163014 0.3337852  0.52763756 0.90128392 0.64928939 0.22096875
 0.16901843 0.60475698 0.8914322  0.06127544 0.16246167 0.71220186
 0.53822404 0.18826028 0.25537412 0.99238449 0.90212023 0.06649267
 0.71204983 0.38052669 0.55154986 0.54473818 0.7134535  0.5738613
 0.44982185 0.57553111 0.66588798 0.24439115 0.35265165 0.27481584]
Mean: 0.47826254267914675


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [57]:
arr = np.random.random((10,10))

print(arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

[[0.94137692 0.06322968 0.60159424 0.4741185  0.07630616 0.14513457
  0.55350524 0.43907639 0.01364591 0.82325536]
 [0.75264501 0.09679693 0.45960203 0.88272141 0.65486614 0.5046083
  0.71138243 0.42162063 0.69837739 0.32918356]
 [0.45710397 0.77456881 0.94899503 0.16785535 0.94073161 0.27207923
  0.44636221 0.05195376 0.04395534 0.349472  ]
 [0.74167495 0.8556764  0.7876201  0.59929938 0.89698074 0.14365646
  0.31223491 0.2307337  0.02281449 0.27022419]
 [0.46007935 0.2496722  0.78046067 0.48856776 0.54195966 0.47705308
  0.59096861 0.31084597 0.00121996 0.71985442]
 [0.06312683 0.17033362 0.54061803 0.38145386 0.5978355  0.48722119
  0.25954919 0.82861978 0.33591783 0.64003792]
 [0.38978184 0.75746283 0.47947858 0.09654931 0.02291531 0.78418664
  0.10597354 0.37522313 0.30412496 0.12083537]
 [0.26411234 0.3403642  0.43818269 0.80996294 0.68517253 0.46580964
  0.99225075 0.70742774 0.46494638 0.81496157]
 [0.46092583 0.50319737 0.91229829 0.68118372 0.40183614 0.83540341
  0.88152841 

6. Create a zero array of size 10 and replace 5th element with 1.


In [58]:
arr = np.zeros(10)

arr[4] = 1

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [59]:
arr = np.array([1,2,0,0,4,0])

reverse = arr[::-1]

print(reverse)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [60]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [61]:
arr = np.zeros((8,8),dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem- 3: Array Operations:<br>
For the following arrays:<br>
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);<br>
v = np.array([9,10]) and w = np.array([11,12]);<br>

In [62]:
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]


1. Add the two array.


In [64]:
add_xy = x + y
print("x + y:\n", add_xy)

x + y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array.


In [65]:
sub_xy = x - y
print("x - y:\n", sub_xy)

x - y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [67]:
mul_x = 3 * x
mul_y = 4 * y
print("3 * x:\n", mul_x)
print("4 * y:\n", mul_y)

3 * x:
 [[ 3  6]
 [ 9 15]]
4 * y:
 [[20 24]
 [28 32]]


4. Find the square of each element of the array.


In [68]:
sq_x = np.square(x)
sq_y = np.square(y)
print("x^2 element-wise:\n", sq_x)
print("y^2 element-wise:\n", sq_y)

x^2 element-wise:
 [[ 1  4]
 [ 9 25]]
y^2 element-wise:
 [[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [69]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("v dot w =", dot_vw)
print("x dot v =", dot_xv)
print("x dot y:\n", dot_xy)

v dot w = 219
x dot v = [29 77]
x dot y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.


In [70]:
concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows (axis=0):\n", concat_xy_rows)

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_cols = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along columns:\n", concat_vw_cols)

Concatenate x and y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [72]:
try:
    bad_concat = np.concatenate((x, v), axis=0)
    print(bad_concat)
except ValueError as e:
    print("Error:", e)
    print("Reason: x is 2D shape", x.shape, "but v is 1D shape", v.shape,
          "→ cannot concatenate arrays with different dimensions.")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D shape (2, 2) but v is 1D shape (2,) → cannot concatenate arrays with different dimensions.


Problem- 4: Matrix Operations:<br>
• For the following arrays:<br>
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]) <br>

In [73]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("A:\n", A)
print("B:\n", B)

A:
 [[3 4]
 [7 8]]
B:
 [[5 3]
 [2 1]]


1. Prove A.A−1 = I.


In [74]:
A_inv = np.linalg.inv(A)
I = np.eye(A.shape[0])

print("A inverse:\n", A_inv)
print("A @ A_inv:\n", A @ A_inv)
print("Is A @ A_inv close to I?", np.allclose(A @ A_inv, I))

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A @ A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A @ A_inv close to I? True


2. Prove AB̸ = BA.


In [75]:
AB = A @ B
BA = B @ A

print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


3. Prove (AB)T = BTAT.


In [76]:
left = (A @ B).T
right = B.T @ A.T

print("(AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Are they equal?", np.allclose(left, right))

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.


Step 1: Write as AX=C

In [77]:
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)

C = np.array([-1, -3, 9], dtype=float)

print("A_sys:\n", A_sys)
print("C:\n", C)

A_sys:
 [[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]
C:
 [-1. -3.  9.]


Step 2: Solve using inverse

In [78]:
X = np.linalg.inv(A_sys) @ C
print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]
